version: '3.8'

services:

  # Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel12-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    environment:
      - APP_ENV=production
      - APP_KEY=base64:r9aO11ff/++ByMv4HBfEdEwzC2a/DBufC3PmzIown+Y=
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel12_db
      - DB_USERNAME=xqyo
      - DB_PASSWORD=secure123
    networks:
      - laravel12-net
    depends_on:
      mysql:
        condition: service_healthy

  # Nginx
  nginx:
    image: nginx:1.25-alpine
    container_name: laravel12-nginx
    restart: always
    ports:
      - "18082:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel12-net
    depends_on:
      - app

  # MySQL 8 (Sudah DIKUNCI dengan data asli kamu)
  mysql:
    image: mysql:8.0
    container_name: laravel12-mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: laravel12_db
      MYSQL_USER: xqyo
      MYSQL_PASSWORD: secure123
      MYSQL_ROOT_PASSWORD: secure123
    volumes:
      - mysql12_data:/var/lib/mysql
    networks:
      - laravel12-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7.2-alpine
    container_name: laravel12-redis
    restart: always
    ports:
      - "16379:6379"
    volumes:
      - redis12_data:/data
    networks:
      - laravel12-net

  # phpMyAdmin (Sudah disesuaikan password root-nya)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel12-phpmyadmin
    restart: always
    ports:
      - "18081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secure123
    networks:
      - laravel12-net
    depends_on:
      - mysql

networks:
  laravel12-net:
    driver: bridge

volumes:
  mysql12_data:
    driver: local
  redis12_data:
    driver: local